---

- hosts: k8s_lb
  become: true
  roles:
    - k8s_lb

- hosts: k8s_controllers[0]
  become: true
  roles:
    - k8s_workers
    - k8s_controllers

- hosts: k8s_controllers:!k8s_controllers[0]
  become: true
  roles:
    - k8s_controllers
    - k8s_workers
  when: inventory_hostname in groups['k8s_controllers'][0]

- hosts: k8s_workers
  become: true
  roles:
    - k8s_workers

