---

- hosts: k8s
  become: true
  pre_tasks:

  - name: ensure old files are not installed
    tags: always
    apt:
      name:
        - curl
        - apt-transport-https
        - gnupg2
        - software-properties-common
        - ca-certificates
        - conatinerd.io
        - kubeadm
        - kubectl
        - kubelet
        - docker-ce
        - docker-ce-cli
        - docker-compose-plugin
      state: absent
  
  - name: install required apps
    tags: always
    apt:
      name:
        - curl
        - apt-transport-https
        - gnupg2
        - software-properties-common
        - ca-certificates
      state: latest
      update_cache: true
    changed_when: false

- hosts: k8s_controllers[0]
  become: true
  roles:
    - k8s_workers
    - k8s_controllers

- hosts: k8s_controllers:!k8s_controllers[0]
  become: true
  roles:
    - k8s_controllers
    - k8s_workers
  when: inventory_hostname in groups['k8s_controllers'][0]

- hosts: k8s_workers
  become: true
  roles:
    - k8s_workers

