---

# Prepare the Load Balancers

- hosts: k8s_lb
  become: true
  roles:
    - k8s_lb

# Create Master node and bootstrap the cluster

- hosts: k8s_controllers[0]
  become: true
  roles:
    - k8s_workers
    - k8s_master

# Join the other Control Planes

- hosts: k8s_controllers:!k8s_controllers[0]
  become: true
  roles:
    - k8s_workers
    - k8s_controllers

# Create and join the workers

- hosts: k8s_workers
  become: true
  roles:
    - k8s_workers

- hosts: k8s_workers
  become: true
  tasks:

    - name: join worker to cluster
      command: "{{ hostvars[groups['k8s_controllers'][0]]['workerjoin'] }}"