---

# Prepare all K8s Nodes

- hosts: k8s
  become: true
  roles:
    - base

# Prepare the Load Balancers

- hosts: k8s_lb
  become: true
  roles:
    - k8s_lb

# Create Master node and bootstrap the cluster

- hosts: k8s_controllers[0]
  become: true
  roles:
    - k8s_master

# Join the other Control Planes

- hosts: k8s_controllers:!k8s_controllers[0]
  become: true
  roles:
    - k8s_controllers

# Join the workers

- hosts: k8s_workers
  become: true
  tasks:

    - name: join worker to cluster
      command: "{{ hostvars[groups['k8s_controllers'][0]]['workerjoin'] }}"