- name: Setup base for Debian
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Setup base for RedHat
  import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'