- name: Install updates
  tags: always
  apt:
    upgrade: dist
    update_cache: yes

- name: install text editors
  tags: always
  apt:
    name: 
      - vim
      - nano
    state: latest

- name: install QEMU guest agent if Proxmox VM
  tags: qemu,vm,proxmox
  apt:
    name: qemu-guest-agent
    state: latest
  when: ansible_system_vendor == "QEMU"

- name: start and enable guest agent service
  tags: qemu,vm,proxmox
  service:
    name: qemu-guest-agent
    state: started
    enabled: true
  when: ansible_system_vendor == "QEMU"

- name: create ssh user
  user:
    name: "{{ ssh_user }}"
        
- name: add ssh key
  tags: always
  authorized_key:
    user: "{{ ssh_user }}"
    key: "{{ ssh_pub_key }}"

- name: add sudoers file
  tags: always
  template:
    src: sudoer_ansible.j2
    dest: "/etc/sudoers.d/sudoer_{{ ssh_user }}"
    owner: root
    group: root
    mode: 0440